import type { Metadata } from "next";
import "./globals.css";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // bisa pilih sesuai kebutuhan
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <script
          dangerouslySetInnerHTML={{
            __html: `if (globalThis.window) window.__RADIX_DISABLE_HYDRATION__ = true;`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
